# BÀI TẬP: EDA HOÀN CHỈNH — TITANIC
## Data Profiling → Descriptive Statistics → Define the Question
**Nguồn:** kaggle.com/c/titanic (891 dòng)

```
PHẦN A — DATA PROFILING       : dữ liệu sạch chưa, có gì
PHẦN B — DESCRIPTIVE STATS    : từng biến trông như thế nào
PHẦN C — DEFINE THE QUESTION  : đặt câu hỏi kinh doanh, trả lời bằng code, rút insight
```

## Setup

In [3]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')

csv_path = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv'

df = pd.read_csv(csv_path)
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [100]:
# TODO
datasize=df.size
print(datasize)

column_name=df.columns
print(column_name)

data_type=df.dtypes
print(data_type)

13365
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')
survived         int64
pclass           int64
sex                str
age            float64
sibsp            int64
parch            int64
fare           float64
embarked           str
class              str
who                str
adult_male        bool
deck               str
embark_town        str
alive              str
alone             bool
dtype: object

## A.2. Missing values & Duplicate data

In [112]:
# Kiem tra null
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [123]:
df.duplicated().sum() #kiem tra trung

np.int64(107)

## A.3. Invalid values

In [134]:
# TODO
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

## A.4. Create a new column
Tạo cột `family_size` = sibsp + parch + 1.

In [155]:
# TODO
df['family_size']=df['sibsp']+df['parch']+1
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [172]:
# tinh trung binh tuoi va ve
print(df[['age','fare']].mean())

age     29.699118
fare    32.204208
dtype: float64

In [181]:
#tinh trung vi tuoi va ve
print(df[['age','fare']].median())

age     28.0000
fare    14.4542
dtype: float64

## Group 2 — Dispersion

In [189]:
# chenh lech do tuoi
range_age=df['age'].max()-df['age'].min()
print(range_age)

79.58

In [217]:
#tinh do lech chua std cua tuoi va gia ve
std_age=df['age'].std()
print(std_age)

#tinh do lech chuan std cua gia ve
print(df['fare'].std())

14.526497332334042
49.6934285971809

In [224]:
#tinh phuong sai cua gia ve
print(df['fare'].var())

2469.436845743116

## Group 3 — Location and Shape

In [231]:
# vi tri data
df.describe()

,survived,pclass,age,sibsp,parch,fare,family_size
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,1.904602
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,1.613459
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,1.000000
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,1.000000
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,2.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,11.000000

In [237]:
df_numeric = df.select_dtypes(include='number')
#do lech
print(df_numeric.skew())

#do nhon
print(df_numeric.kurt())

survived       0.478523
pclass        -0.630548
age            0.389108
sibsp          3.695352
parch          2.749117
fare           4.787317
family_size    2.727441
dtype: float64
survived       -1.775005
pclass         -1.280015
age             0.178274
sibsp          17.880420
parch           9.778125
fare           33.398141
family_size     9.159666
dtype: float64

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Hạng vé nào có tỷ lệ sống sót cao nhất, chênh lệch bao nhiêu so với hạng thấp nhất?

In [278]:
# TODO

survival_class=df.groupby('class')['survived'].mean()*100
print(survival_class.sort_values(ascending=False))
max_survival_Class=survival_class.max()
min_survival_Class=survival_class.min()
#hang ve co ti le song sot cao nhat
print("Hang first co ti le song sot cao nhat: ",max_survival)

#chenh lech
chenhLechTLSongCLass=max_survival_Class-min_survival_Class
print("Chenh lech min max survived: ",chenhLechTLSongCLass)

class
First     62.962963
Second    47.282609
Third     24.236253
Name: survived, dtype: float64
Hang first co ti le song sot cao nhat:  62.96296296296296
Chenh lech min max survived:  38.726710417138115

## Câu hỏi 2: Giới tính hay hạng vé ảnh hưởng đến sống sót mạnh hơn?

In [283]:
# gom nhom theo gioi tinh
gender_survival=df.groupby('sex')['survived'].mean()*100
print(gender_survival.sort_values(ascending=False))
max_survival_gender=gender_survival.max()
min_survival_genger=gender_survival.min()
chenhLechTLSongGender=max_survival_gender-min_survival_genger

if(chenhLechTLSongCLass>chenhLechTLSongGender):
    print("Ket luan: ti le song theo class cao hon theo gioi tinh")
else:
    print("Ket luan: ti le song theo gioi tinh cao hon theo class")

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64
Ket luan: ti le song theo gioi tinh cao hon theo class

## Câu hỏi 3: Vé đắt hơn có thực sự sống sót cao hơn không?

In [312]:
fare_suvived=df.groupby('survived')['fare'].median()
print(fare_suvived.sort_values(ascending=False))

chenhLechGiaVe=fare_suvived[1]-fare_suvived[0]
print("Nguoi song sot mua ve cao hon nguoi khong qua khoi la: ", chenhLechGiaVe)

survived
1    26.0
0    10.5
Name: fare, dtype: float64
Nguoi song sot mua ve cao hon nguoi khong qua khoi la:  15.5

## Câu hỏi 4: Gia đình đông người có ảnh hưởng đến khả năng sống sót không?

In [329]:
family_sur=df.groupby('family_size')['survived'].mean()
max_fam_sur=family_sur.max()
min_fam_sur=family_sur.min()
print(family_sur.sort_values(ascending=False))

print("Gia dinh tu 2 toi 4 nguoi co ti le song sot cao: 55 den 72% ")
print("Gia dinh tu 5 toi 11 nguoi co ti le song sot thap: 2 den 0% ")

family_size
4     0.724138
3     0.578431
2     0.552795
7     0.333333
1     0.303538
5     0.200000
6     0.136364
8     0.000000
11    0.000000
Name: survived, dtype: float64
Gia dinh tu 2 toi 4 nguoi co ti le song sot cao: 55 den 72%
Gia dinh tu 5 toi 11 nguoi co ti le song sot thap: 2 den 0%

## Câu hỏi 5: Cảng lên tàu (embark_town) nào có tỷ lệ sống sót cao nhất?

In [334]:
sur_embark_town=df.groupby('embark_town')['survived'].mean()*100

print(sur_embark_town)

max_sur_em=sur_embark_town.max()
print("Cang len tau Cherbourg co ty le song sot cao nhat: ", max_sur_em)

embark_town
Cherbourg      55.357143
Queenstown     38.961039
Southampton    33.695652
Name: survived, dtype: float64
Cang len tau Cherbourg co ty le song sot cao nhat:  55.35714285714286

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể về dữ liệu Titanic.

*Số người trên tàu tầm 29 tuổi.* 
*Hạng vé cao hơn có tỉ lệ sống sót cao hơn.*
*Giá vé đắt hơn có tỉ lệ sống cao hơn.*
*Nữ có tỉ lệ sống sót cao hơn nam.* 
*Gia đình khoảng 4-5 người tỉ lệ sống cao hơn vì có thể hỗ trợ lẫn nhau.*